/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorHistorial;
import Modelo.Historiales;
import Modelo.Usuario;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;

/**
 *
 * @author sotog
 */
public class VistaMenu extends javax.swing.JFrame {
    Usuario usuario;
    Controlador.ControladorHistorial controH;
    /**
     * Creates new form VistaMenu
     */
    public VistaMenu(Usuario usuarios ) {
        initComponents();
        setLocationRelativeTo(this);
        this.usuario = usuarios;
        controH= new ControladorHistorial();
        jLabel1.setText(usuario.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnIibro = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        btnGeneros = new javax.swing.JButton();
        btnDevoluciones = new javax.swing.JButton();
        btnIibro1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 13, 18));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(24, 61, 61));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/bookshelf-in-library-vector.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(147, 177, 166));
        jLabel1.setText("Menu");

        btnUsuarios.setBackground(new java.awt.Color(24, 61, 61));
        btnUsuarios.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(147, 177, 166));
        btnUsuarios.setText("Gestionar usuario");
        btnUsuarios.setActionCommand("Inicio");
        btnUsuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseMoved(evt);
            }
        });
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnIibro.setBackground(new java.awt.Color(24, 61, 61));
        btnIibro.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnIibro.setForeground(new java.awt.Color(147, 177, 166));
        btnIibro.setText("Gestionar libros");
        btnIibro.setActionCommand("Inicio");
        btnIibro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnIibroMouseMoved(evt);
            }
        });
        btnIibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIibroActionPerformed(evt);
            }
        });

        btnHistorial.setBackground(new java.awt.Color(24, 61, 61));
        btnHistorial.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(147, 177, 166));
        btnHistorial.setText("Ver historial");
        btnHistorial.setActionCommand("Inicio");
        btnHistorial.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHistorialMouseMoved(evt);
            }
        });
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        btnPrestamos.setBackground(new java.awt.Color(24, 61, 61));
        btnPrestamos.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnPrestamos.setForeground(new java.awt.Color(147, 177, 166));
        btnPrestamos.setText("Gestionar prestamos");
        btnPrestamos.setActionCommand("Inicio");
        btnPrestamos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseMoved(evt);
            }
        });
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });

        btnGeneros.setBackground(new java.awt.Color(24, 61, 61));
        btnGeneros.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnGeneros.setForeground(new java.awt.Color(147, 177, 166));
        btnGeneros.setText("Gestionar generos");
        btnGeneros.setActionCommand("Inicio");
        btnGeneros.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnGenerosMouseMoved(evt);
            }
        });
        btnGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerosActionPerformed(evt);
            }
        });

        btnDevoluciones.setBackground(new java.awt.Color(24, 61, 61));
        btnDevoluciones.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnDevoluciones.setForeground(new java.awt.Color(147, 177, 166));
        btnDevoluciones.setText("Gestionar devoluciones");
        btnDevoluciones.setActionCommand("Inicio");
        btnDevoluciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDevolucionesMouseMoved(evt);
            }
        });
        btnDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionesActionPerformed(evt);
            }
        });

        btnIibro1.setBackground(new java.awt.Color(24, 61, 61));
        btnIibro1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnIibro1.setForeground(new java.awt.Color(147, 177, 166));
        btnIibro1.setText("Reportes");
        btnIibro1.setActionCommand("Inicio");
        btnIibro1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnIibro1MouseMoved(evt);
            }
        });
        btnIibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIibro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIibro1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHistorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIibro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(btnGeneros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDevoluciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(177, 177, 177)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(btnUsuarios)
                .addGap(18, 18, 18)
                .addComponent(btnGeneros)
                .addGap(18, 18, 18)
                .addComponent(btnIibro)
                .addGap(18, 18, 18)
                .addComponent(btnHistorial)
                .addGap(18, 18, 18)
                .addComponent(btnPrestamos)
                .addGap(18, 18, 18)
                .addComponent(btnDevoluciones)
                .addGap(12, 12, 12)
                .addComponent(btnIibro1)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jMenu1.setText("Más");

        jMenuItem2.setText("Cerrar sesión");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         try {

            LocalDate fechaActual = LocalDate.now();
            LocalTime horaActual = LocalTime.now();
            Usuario id_usuar = controH.buscarUsuarioPorCedula(usuario.getCedula());
            int usuarioss = id_usuar.getCedula();

            String accion = "Cerró sesión una persona con cedula: " + usuario.getCedula();
            Historiales historial = new Historiales(0, fechaActual, horaActual, usuario.getNombre(), accion, usuarioss);
            controH.agregarRegistroHistorial(historial);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error al generar acción");
        }
        new VistaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
         btnUsuarios.setForeground(Color.lightGray);
         btnHistorial.setForeground(Color.lightGray);
         btnIibro.setForeground(Color.lightGray);
         btnPrestamos.setForeground(Color.lightGray);
         btnDevoluciones.setForeground(Color.lightGray);
    }//GEN-LAST:event_jPanel1MouseMoved

    private void btnUsuariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseMoved
        // TODO add your handling code here:
        btnUsuarios.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnUsuariosMouseMoved

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        new VistaUsuario(usuario).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnIibroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIibroMouseMoved
        // TODO add your handling code here:
        
         btnIibro.setForeground(Color.WHITE);
         
    }//GEN-LAST:event_btnIibroMouseMoved

    private void btnIibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIibroActionPerformed
        // TODO add your handling code here:
        VistaLibro ventana = new VistaLibro(usuario);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIibroActionPerformed

    private void btnHistorialMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialMouseMoved
        // TODO add your handling code here:
     
         btnHistorial.setForeground(Color.WHITE);
       
    }//GEN-LAST:event_btnHistorialMouseMoved

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        new Historial(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnPrestamosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseMoved
        // TODO add your handling code here:
       
         btnPrestamos.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnPrestamosMouseMoved

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        // TODO add your handling code here:
        new VistaPrestramo(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void btnGenerosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerosMouseMoved
        // TODO add your handling code here:
        btnGeneros.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnGenerosMouseMoved

    private void btnGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerosActionPerformed
        // TODO add your handling code here:
        new VistaGeneroLibros(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenerosActionPerformed

    private void btnDevolucionesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolucionesMouseMoved
        // TODO add your handling code here:
        btnDevoluciones.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnDevolucionesMouseMoved

    private void btnDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionesActionPerformed
        // TODO add your handling code here:
        new VistaDevolucion(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDevolucionesActionPerformed

    private void btnIibro1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIibro1MouseMoved
        // TODO add your handling code here:

        btnIibro.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnIibro1MouseMoved

    private void btnIibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIibro1ActionPerformed
        // TODO add your handling code here:
        VistaReportes ventana = new VistaReportes(usuario);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIibro1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevoluciones;
    private javax.swing.JButton btnGeneros;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnIibro;
    private javax.swing.JButton btnIibro1;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
