/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorHistorial;
import Controlador.ControladorPrestamoDevolucion;
import Modelo.Historiales;
import Modelo.PrestamoDevolucion;
import Modelo.Usuario;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import util.Pdf;

/**
 *
 * @author sotog
 */
public class VistaReporUsuarios extends javax.swing.JFrame {

    Usuario usuario;
    ControladorHistorial controH;
    Pdf pdf;
    ArrayList<Historiales> lista;

    /**
     * Creates new form VistaReporDevoluciones
     */
    public VistaReporUsuarios(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(this);
        this.usuario = usuario;
        controH= new ControladorHistorial();
        pdf = new Pdf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnReporteUsuariosCreados = new javax.swing.JButton();
        btnReporteUsuariosModificados = new javax.swing.JButton();
        btnReporteUsuariosEliminados = new javax.swing.JButton();
        btnReporteUsuariosLogueados = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 13, 18));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(24, 61, 61));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/bookshelf-in-library-vector.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(147, 177, 166));
        jLabel1.setText("Reportes de los usuarios:");

        btnReporteUsuariosCreados.setBackground(new java.awt.Color(24, 61, 61));
        btnReporteUsuariosCreados.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnReporteUsuariosCreados.setForeground(new java.awt.Color(147, 177, 166));
        btnReporteUsuariosCreados.setText("Generar reporte usuarios creados");
        btnReporteUsuariosCreados.setActionCommand("Inicio");
        btnReporteUsuariosCreados.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnReporteUsuariosCreadosMouseMoved(evt);
            }
        });
        btnReporteUsuariosCreados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteUsuariosCreadosActionPerformed(evt);
            }
        });

        btnReporteUsuariosModificados.setBackground(new java.awt.Color(24, 61, 61));
        btnReporteUsuariosModificados.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnReporteUsuariosModificados.setForeground(new java.awt.Color(147, 177, 166));
        btnReporteUsuariosModificados.setText("Generar reporte usuarios modificados");
        btnReporteUsuariosModificados.setActionCommand("Inicio");
        btnReporteUsuariosModificados.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnReporteUsuariosModificadosMouseMoved(evt);
            }
        });
        btnReporteUsuariosModificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteUsuariosModificadosActionPerformed(evt);
            }
        });

        btnReporteUsuariosEliminados.setBackground(new java.awt.Color(24, 61, 61));
        btnReporteUsuariosEliminados.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnReporteUsuariosEliminados.setForeground(new java.awt.Color(147, 177, 166));
        btnReporteUsuariosEliminados.setText("Generar reporte usuarios eliminados");
        btnReporteUsuariosEliminados.setActionCommand("Inicio");
        btnReporteUsuariosEliminados.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnReporteUsuariosEliminadosMouseMoved(evt);
            }
        });
        btnReporteUsuariosEliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteUsuariosEliminadosActionPerformed(evt);
            }
        });

        btnReporteUsuariosLogueados.setBackground(new java.awt.Color(24, 61, 61));
        btnReporteUsuariosLogueados.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnReporteUsuariosLogueados.setForeground(new java.awt.Color(147, 177, 166));
        btnReporteUsuariosLogueados.setText("Generar reporte usuarios logueados");
        btnReporteUsuariosLogueados.setActionCommand("Inicio");
        btnReporteUsuariosLogueados.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnReporteUsuariosLogueadosMouseMoved(evt);
            }
        });
        btnReporteUsuariosLogueados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteUsuariosLogueadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReporteUsuariosModificados, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporteUsuariosCreados, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporteUsuariosEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporteUsuariosLogueados, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnReporteUsuariosCreados)
                .addGap(46, 46, 46)
                .addComponent(btnReporteUsuariosModificados)
                .addGap(41, 41, 41)
                .addComponent(btnReporteUsuariosEliminados)
                .addGap(35, 35, 35)
                .addComponent(btnReporteUsuariosLogueados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Más");

        jMenuItem2.setText("Volver");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved


    }//GEN-LAST:event_jPanel1MouseMoved

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        new VistaReportes(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnReporteUsuariosCreadosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteUsuariosCreadosMouseMoved
        // TODO add your handling code here:
        btnReporteUsuariosCreados.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnReporteUsuariosCreadosMouseMoved

    private void btnReporteUsuariosCreadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteUsuariosCreadosActionPerformed
        try {
            lista = controH.listaUsuariosCreados();
            pdf.pdfUsuariosCreados(lista);
            LocalDate fechaActual = LocalDate.now();
            LocalTime horaActual = LocalTime.now();
            Usuario id_usuar = controH.buscarUsuarioPorCedula(usuario.getCedula());
            int usuarioss = id_usuar.getCedula();
               

                String accion = "Se genero un reporte de los usuarios creados " ;
                Historiales historial = new Historiales(0, fechaActual, horaActual, usuario.getNombre(), accion, usuarioss);
                controH.agregarRegistroHistorial(historial);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error al generar el reporte");
        }
    }//GEN-LAST:event_btnReporteUsuariosCreadosActionPerformed

    private void btnReporteUsuariosModificadosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteUsuariosModificadosMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteUsuariosModificadosMouseMoved

    private void btnReporteUsuariosModificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteUsuariosModificadosActionPerformed
        // TODO add your handling code here:
        try {
            lista = controH.listaUsuariosModificados();
            pdf.pdfUsuariosModificados(lista);
            LocalDate fechaActual = LocalDate.now();
            LocalTime horaActual = LocalTime.now();
            Usuario id_usuar = controH.buscarUsuarioPorCedula(usuario.getCedula());
            int usuarioss = id_usuar.getCedula();
               

                String accion = "Se genero un reporte de los usuarios modificados " ;
                Historiales historial = new Historiales(0, fechaActual, horaActual, usuario.getNombre(), accion, usuarioss);
                controH.agregarRegistroHistorial(historial);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error al generar el reporte");
        }
    }//GEN-LAST:event_btnReporteUsuariosModificadosActionPerformed

    private void btnReporteUsuariosEliminadosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteUsuariosEliminadosMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteUsuariosEliminadosMouseMoved

    private void btnReporteUsuariosEliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteUsuariosEliminadosActionPerformed
        // TODO add your handling code here:
        
        try {
            lista = controH.listaUsuariosEliminados();
            pdf.pdfUsuariosEliminados(lista);
            LocalDate fechaActual = LocalDate.now();
            LocalTime horaActual = LocalTime.now();
            Usuario id_usuar = controH.buscarUsuarioPorCedula(usuario.getCedula());
            int usuarioss = id_usuar.getCedula();
               

                String accion = "Se genero un reporte de los usuarios eliminados " ;
                Historiales historial = new Historiales(0, fechaActual, horaActual, usuario.getNombre(), accion, usuarioss);
                controH.agregarRegistroHistorial(historial);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error al generar el reporte");
        }
    }//GEN-LAST:event_btnReporteUsuariosEliminadosActionPerformed

    private void btnReporteUsuariosLogueadosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteUsuariosLogueadosMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteUsuariosLogueadosMouseMoved

    private void btnReporteUsuariosLogueadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteUsuariosLogueadosActionPerformed
        // TODO add your handling code here:
        try {
            lista = controH.listaUsuariosLogueados();
            pdf.pdfUsuariosLogueados(lista);
            LocalDate fechaActual = LocalDate.now();
            LocalTime horaActual = LocalTime.now();
            Usuario id_usuar = controH.buscarUsuarioPorCedula(usuario.getCedula());
            int usuarioss = id_usuar.getCedula();
               

                String accion = "Se genero un reporte de los usuarios logueados " ;
                Historiales historial = new Historiales(0, fechaActual, horaActual, usuario.getNombre(), accion, usuarioss);
                controH.agregarRegistroHistorial(historial);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error al generar el reporte");
        }
    }//GEN-LAST:event_btnReporteUsuariosLogueadosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteUsuariosCreados;
    private javax.swing.JButton btnReporteUsuariosEliminados;
    private javax.swing.JButton btnReporteUsuariosLogueados;
    private javax.swing.JButton btnReporteUsuariosModificados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
